export const SET_CART = 'cart/setCart'
export const DELETE_CART = 'cart/deleteCart'
export const SET_LOADING = 'loading/setLoading'
export const SET_ERROR = 'error/setError'
export const SET_USER = 'user/setUser'